#!/usr/bin/env node
// Seed loader: reads the seed JSON files and emits idempotent SQL for
// `wrangler d1 execute`. Usage:
//   node packages/schema/seed/load.js            # SQL to stdout
//   node packages/schema/seed/load.js --out f.sql

const fs = require('fs');
const path = require('path');

const SEED_DIR = __dirname;

function sq(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function loadModules() {
  const dir = path.join(SEED_DIR, 'remediation-modules');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => readJson(path.join(dir, f)))
    .sort((a, b) => a.priority - b.priority);
}

function main() {
  const dataClasses = readJson(path.join(SEED_DIR, 'data-classes.json')).classes;
  const stateRights = readJson(path.join(SEED_DIR, 'state-rights.json')).rows;
  const modules = loadModules();

  const knownCodes = new Set(dataClasses.map((c) => c.code));
  const lines = ['-- Generated by packages/schema/seed/load.js. Do not edit.'];

  // remediation_modules
  for (const m of modules) {
    for (const code of m.applies_to) {
      if (!knownCodes.has(code)) {
        throw new Error(`module ${m.slug}: applies_to references unknown data class '${code}'`);
      }
    }
    lines.push(
      `INSERT OR REPLACE INTO remediation_modules (slug, title, applies_to, jurisdiction, priority, body_md, source_url, last_verified) VALUES (` +
        [
          sq(m.slug),
          sq(m.title),
          sq(JSON.stringify(m.applies_to)),
          sq(m.jurisdiction || 'US'),
          sq(m.priority),
          sq(m.body_md),
          sq(m.source_url),
          sq(m.last_verified),
        ].join(', ') +
        `);`
    );
  }

  // data_classes — remediation_ids computed as the inverse of module applies_to,
  // ordered by module priority, so the module library stays the single source
  // of truth (see data-classes.json header comment).
  for (const c of dataClasses) {
    const remediationIds = modules.filter((m) => m.applies_to.includes(c.code)).map((m) => m.slug);
    lines.push(
      `INSERT OR REPLACE INTO data_classes (code, label, permanence, severity_weight, remediation_ids) VALUES (` +
        [sq(c.code), sq(c.label), sq(c.permanence), sq(c.severity_weight), sq(JSON.stringify(remediationIds))].join(', ') +
        `);`
    );
  }

  // state_rights
  const seen = new Set();
  for (const r of stateRights) {
    if (seen.has(r.state_code)) throw new Error(`duplicate state_code ${r.state_code}`);
    seen.add(r.state_code);
    lines.push(
      `INSERT OR REPLACE INTO state_rights (state_code, state_name, notification_deadline_days, ssn_triggers_notice, free_credit_freeze, mandated_monitoring_months, ag_report_threshold, statute_citation, statute_url, last_verified) VALUES (` +
        [
          sq(r.state_code),
          sq(r.state_name),
          sq(r.notification_deadline_days),
          sq(r.ssn_triggers_notice),
          sq(r.free_credit_freeze),
          sq(r.mandated_monitoring_months),
          sq(r.ag_report_threshold),
          sq(r.statute_citation),
          sq(r.statute_url),
          sq(r.last_verified),
        ].join(', ') +
        `);`
    );
  }

  const sql = lines.join('\n') + '\n';
  const outFlag = process.argv.indexOf('--out');
  if (outFlag !== -1 && process.argv[outFlag + 1]) {
    const outPath = process.argv[outFlag + 1];
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, sql);
    console.error(
      `seed SQL written to ${outPath} (${modules.length} modules, ${dataClasses.length} data classes, ${stateRights.length} state rights rows)`
    );
  } else {
    process.stdout.write(sql);
  }
}

main();
