// load.js turns the seed JSON into the SQL that bootstraps the local D1
// database. It is the only place the module library, the data-class weights,
// and the state-rights table are cross-checked against each other, so the
// invariants it enforces are what keep the seeded database internally
// consistent. None of that was tested.
//
// main() runs at require time and writes to stdout, so these tests drive it as
// a subprocess against the real seed files and assert on the SQL it emits.

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const { DatabaseSync } = require('node:sqlite');

const SEED_DIR = path.join(__dirname);
const ROOT = path.join(__dirname, '..', '..');
const LOADER = path.join(SEED_DIR, 'load.js');

const dataClasses = JSON.parse(fs.readFileSync(path.join(SEED_DIR, 'data-classes.json'), 'utf8')).classes;
const stateRights = JSON.parse(fs.readFileSync(path.join(SEED_DIR, 'state-rights.json'), 'utf8')).rows;
const modules = fs
  .readdirSync(path.join(SEED_DIR, 'remediation-modules'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(SEED_DIR, 'remediation-modules', f), 'utf8')))
  .sort((a, b) => a.priority - b.priority);

/** Run the loader and return the SQL it writes to stdout. */
function runLoader(args = []) {
  return execFileSync(process.execPath, [LOADER, ...args], {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

/** The seed data as SQLite actually stores it, from the emitted SQL. */
function loadIntoDb(sql) {
  const db = new DatabaseSync(':memory:');
  // The real migration, not a hand-written stand-in. The PRIMARY KEYs are what
  // make INSERT OR REPLACE idempotent, so a test that invented its own schema
  // would be asserting against tables the project never creates.
  db.exec(
    fs.readFileSync(path.join(SEED_DIR, '..', 'migrations', '0004_reference_tables.sql'), 'utf8')
  );
  db.exec(sql);
  return db;
}

// --- Shape of the emitted script ------------------------------------------

test('emits a generated-file marker so nobody hand-edits the output', () => {
  const sql = runLoader();
  assert.match(sql, /^-- Generated by packages\/schema\/seed\/load\.js\. Do not edit\./);
});

test('every seeded row appears exactly once, for all three tables', () => {
  const sql = runLoader();
  assert.equal(sql.match(/INSERT OR REPLACE INTO remediation_modules/g).length, modules.length);
  assert.equal(sql.match(/INSERT OR REPLACE INTO data_classes/g).length, dataClasses.length);
  assert.equal(sql.match(/INSERT OR REPLACE INTO state_rights/g).length, stateRights.length);
});

test('is idempotent: re-running the same seed twice leaves one row per key', () => {
  // The loader uses INSERT OR REPLACE precisely so `db:reset` can be re-run.
  const sql = runLoader();
  const db = loadIntoDb(sql);
  db.exec(sql);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM data_classes').get().n, dataClasses.length);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM state_rights').get().n, stateRights.length);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM remediation_modules').get().n, modules.length);
});

test('the emitted SQL executes cleanly against the real schema', () => {
  // A single bad literal or a syntax error anywhere would abort the whole
  // `db:seed` run partway through, leaving a half-seeded database.
  const db = loadIntoDb(runLoader());
  assert.ok(db.prepare('SELECT COUNT(*) AS n FROM data_classes').get().n > 0);
});

// --- The cross-table invariant this loader exists to enforce --------------

test('remediation_ids is the exact inverse of module applies_to', () => {
  // The data-classes.json header makes the module library the single source of
  // truth, and this is where that is actually computed. A mismatch would put a
  // remediation step on a data class it does not address, or drop one entirely.
  const db = loadIntoDb(runLoader());
  const rows = db.prepare('SELECT code, remediation_ids FROM data_classes').all();
  for (const row of rows) {
    const expected = modules.filter((m) => m.applies_to.includes(row.code)).map((m) => m.slug);
    assert.deepEqual(JSON.parse(row.remediation_ids), expected, `data class ${row.code}`);
  }
});

test('a class addressed by a module carries a remediation step', () => {
  // The user-visible consequence: every weighted class that a module claims to
  // cover must expose it, or the class renders with no remediation at all.
  const db = loadIntoDb(runLoader());
  const covered = db
    .prepare('SELECT code, remediation_ids FROM data_classes')
    .all()
    .filter((r) => JSON.parse(r.remediation_ids).length > 0);
  assert.ok(covered.length > 0, 'no data class carries a remediation step');
});

test('modules are seeded in priority order, so the first fix offered is the first priority', () => {
  const sql = runLoader();
  const order = [
    ...sql.matchAll(/INSERT OR REPLACE INTO remediation_modules \([^)]*\) VALUES \('([^']*)'/g),
  ].map((m) => m[1]);
  const byPriority = modules.map((m) => m.slug);
  assert.deepEqual(order, byPriority);
});

test('every remediation_id resolves to a module that was actually seeded', () => {
  // A dangling id would render as a link to nothing on the detail page.
  const db = loadIntoDb(runLoader());
  const slugs = new Set(db.prepare('SELECT slug FROM remediation_modules').all().map((r) => r.slug));
  for (const row of db.prepare('SELECT code, remediation_ids FROM data_classes').all()) {
    for (const id of JSON.parse(row.remediation_ids)) {
      assert.ok(slugs.has(id), `${row.code} references unknown module ${id}`);
    }
  }
});

test('every module applies to a data class that exists', () => {
  // load.js throws on this; asserting the seeded data stays consistent is the
  // other half of that guard.
  const codes = new Set(dataClasses.map((c) => c.code));
  for (const m of modules) {
    for (const code of m.applies_to) {
      assert.ok(codes.has(code), `module ${m.slug} applies to unknown data class ${code}`);
    }
  }
});

test('a data class with no module still seeds, with an empty list rather than NULL', () => {
  // [] means "no remediation known"; NULL would render as a missing value.
  const db = loadIntoDb(runLoader());
  for (const row of db.prepare('SELECT code, remediation_ids FROM data_classes').all()) {
    assert.notEqual(row.remediation_ids, null, `${row.code} has NULL remediation_ids`);
    assert.doesNotThrow(() => JSON.parse(row.remediation_ids));
  }
});

// --- state_rights specifics ----------------------------------------------

test('state_codes are unique, which load.js enforces by throwing', () => {
  const seen = new Set();
  for (const r of stateRights) {
    assert.ok(!seen.has(r.state_code), `duplicate state_code ${r.state_code}`);
    seen.add(r.state_code);
  }
  const db = loadIntoDb(runLoader());
  const n = db.prepare('SELECT COUNT(*) AS n FROM state_rights').get().n;
  assert.equal(n, new Set(stateRights.map((r) => r.state_code)).size);
});

test('boolean rights survive as 0/1 integers, not as text', () => {
  // The state-rights table drives rights text on the pages; SQLite has no
  // boolean type, so these must land as integers to be usable in a comparison.
  const db = loadIntoDb(runLoader());
  const rows = db.prepare('SELECT state_code, ssn_triggers_notice, free_credit_freeze FROM state_rights').all();
  assert.ok(rows.length > 0);
  for (const r of rows) {
    for (const col of ['ssn_triggers_notice', 'free_credit_freeze']) {
      const v = r[col];
      assert.ok(v === 0 || v === 1, `${r.state_code}.${col} is ${JSON.stringify(v)}, not 0/1`);
    }
  }
});

test('a state with no fixed deadline keeps NULL rather than a fabricated day count', () => {
  // Several states require notice "without unreasonable delay" and publish no
  // number. Writing 0 or a guess would state a deadline the statute never gave.
  const db = loadIntoDb(runLoader());
  const nulls = db
    .prepare('SELECT COUNT(*) AS n FROM state_rights WHERE notification_deadline_days IS NULL')
    .get().n;
  const sourceNulls = stateRights.filter((r) => r.notification_deadline_days === null).length;
  assert.equal(nulls, sourceNulls);
});

test('every state cites a statute URL, since every published fact needs a source', () => {
  const db = loadIntoDb(runLoader());
  for (const r of db.prepare('SELECT state_code, statute_url FROM state_rights').all()) {
    assert.match(r.statute_url || '', /^https:\/\//, `${r.state_code} has no official statute URL`);
  }
});

// --- Text fidelity --------------------------------------------------------

test('statute citations keep their section signs and em dashes through the SQL', () => {
  // These strings carry non-ASCII on purpose. A truncation or encoding slip
  // here would corrupt a legal citation in the published record.
  const db = loadIntoDb(runLoader());
  const ak = db.prepare("SELECT statute_citation FROM state_rights WHERE state_code = 'AK'").get();
  assert.match(ak.statute_citation, /§/);
});

test('a quote inside a module body is escaped, not injected', () => {
  // The body_md is the only field large and free-form enough to carry a quote
  // that matters; it goes through the shared sqlLiteral like everything else.
  const db = loadIntoDb(runLoader());
  for (const r of db.prepare('SELECT slug, body_md FROM remediation_modules').all()) {
    assert.doesNotThrow(() => db.prepare('SELECT COUNT(*) AS n FROM remediation_modules WHERE slug = ?').get(r.slug));
    assert.notEqual(r.body_md, null, `${r.slug} lost its body`);
  }
});

// --- CLI contract ---------------------------------------------------------

test('--out requires a file path, and fails loudly when given none', () => {
  assert.throws(() => runLoader(['--out']), /--out requires a file path/);
});

test('--out writes the same SQL it would have printed, and reports to stderr', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'seed-out-'));
  const out = path.join(dir, 'nested', 'seed.sql');
  const stdout = execFileSync(process.execPath, [LOADER, '--out', out], {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  assert.equal(stdout, '', 'SQL belongs in the file, not on stdout');
  assert.equal(fs.readFileSync(out, 'utf8'), runLoader());
  fs.rmSync(dir, { recursive: true, force: true });
});
