// JSF form-driving helpers for the HHS OCR breach portal.
//
// The portal is a Mojarra/PrimeFaces JavaServer Faces app. There is no static
// CSV URL: obtaining the export requires a cookie-bound, multi-step POST
// sequence carrying a javax.faces.ViewState token that changes at every step.
//
// Every element id in that sequence (ocrForm:j_idt384 and friends) is
// auto-generated by Mojarra and SHIFTS WHENEVER HHS REDEPLOYS — a 2019 capture
// used j_idt364 for the same CSV link that a 2026 capture calls j_idt384.
// Nothing here may hardcode one. Commands are discovered structurally, by the
// label or icon a human would click, and a failed discovery throws with the
// surrounding markup so the breakage is diagnosable instead of silent.
//
// These functions are pure string-in/string-out so they can be tested without
// network access; the orchestration that uses them lives in hhs-ocr-fetch.js.

/** Collect every hidden input as name -> value. */
function extractHiddenInputs(html) {
  const out = {};
  const inputRe = /<input\b[^>]*>/gi;
  let m;
  while ((m = inputRe.exec(html))) {
    const tag = m[0];
    if (!/type\s*=\s*["']?hidden/i.test(tag)) continue;
    const name = /\bname\s*=\s*["']([^"']+)["']/i.exec(tag);
    if (!name) continue;
    const value = /\bvalue\s*=\s*["']([^"']*)["']/i.exec(tag);
    out[name[1]] = value ? decodeEntities(value[1]) : '';
  }
  return out;
}

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

/**
 * The ViewState token. Accepts the Jakarta Faces 4 spelling too, so a platform
 * upgrade downgrades to a clear error rather than a silent 'not found'.
 */
function extractViewState(hidden) {
  return hidden['javax.faces.ViewState'] ?? hidden['jakarta.faces.ViewState'] ?? null;
}

/** The <form> action attribute (may carry a path-encoded ;jsessionid=...). */
function extractFormAction(html, formId = 'ocrForm') {
  const re = new RegExp(`<form\\b[^>]*\\bid\\s*=\\s*["']${formId}["'][^>]*>`, 'i');
  const tag = re.exec(html);
  if (!tag) return null;
  const action = /\baction\s*=\s*["']([^"']+)["']/i.exec(tag[0]);
  return action ? decodeEntities(action[1]) : null;
}

/**
 * Find the JSF command id behind a link, by the visible text a human clicks.
 * Mojarra renders these as:
 *   <a href="#" onclick="mojarra.jsfcljs(document.getElementById('ocrForm'),
 *      {'ocrForm:j_idt39':'ocrForm:j_idt39'},'');return false">View HIPAA Breach Reports</a>
 */
function findCommandByLabel(html, label) {
  const wanted = label.toLowerCase().replace(/\s+/g, ' ').trim();
  for (const c of listCommandCandidates(html)) {
    if (c.label.toLowerCase().includes(wanted)) return c.commandId;
  }
  return null;
}

// A JSF command can be triggered from an <a>, a <button>, or a PrimeFaces
// widget, and can be wired through mojarra.jsfcljs (non-AJAX) or PrimeFaces.ab
// (AJAX). Match the element generically rather than assuming an anchor.
const COMMAND_ELEMENT_RE =
  /<(a|button|span|div|li)\b([^>]*\bonclick\s*=\s*"([^"]*(?:mojarra\.jsfcljs|PrimeFaces\.ab|PrimeFaces\.addSubmitParam)[^"]*)"[^>]*)>([\s\S]*?)<\/\1>/gi;

function commandIdFrom(onclick) {
  const decoded = decodeEntities(onclick);
  // mojarra.jsfcljs(form, {'ocrForm:j_idt384':'ocrForm:j_idt384'}, '')
  const mojarra = /\{\s*'([^']+)'\s*:/.exec(decoded);
  if (mojarra) return mojarra[1];
  // PrimeFaces.ab({s:"ocrForm:j_idt384", ...})
  const pf = /\bs\s*:\s*["']([^"']+)["']/.exec(decoded);
  if (pf) return pf[1];
  return null;
}

/**
 * Find the CSV export command.
 *
 * The exporters (Excel, PDF, CSV, XML) sit together, so selection MUST be by
 * what identifies CSV specifically — picking by position silently downloads a
 * spreadsheet that the parser will reject or, worse, misread.
 *
 * The portal runs PrimeFaces 12, which renders exporters as icon-font elements
 * (primeicons) rather than the <img alt="CSV"> markup that older scrapers
 * document, so every plausible CSV signal is checked: alt/title/aria-label
 * text, icon class names, element id, and visible label text.
 */
function findCsvExportCommand(html) {
  const candidates = listCommandCandidates(html);
  for (const c of candidates) {
    if (c.isCsv) return c.commandId;
  }
  return null;
}

/** Every JSF command on the page, annotated — used for discovery and for
 *  diagnosing a portal redesign without another round trip. */
function listCommandCandidates(html) {
  const out = [];
  let m;
  COMMAND_ELEMENT_RE.lastIndex = 0;
  while ((m = COMMAND_ELEMENT_RE.exec(html))) {
    const attrs = m[2] || '';
    const inner = m[4] || '';
    const commandId = commandIdFrom(m[3] || '');
    if (!commandId) continue;
    const haystack = `${attrs} ${inner}`;
    const label = inner.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
    const isCsv =
      /\b(?:alt|title|aria-label)\s*=\s*["'][^"']*\bcsv\b[^"']*["']/i.test(haystack) ||
      /\bsrc\s*=\s*["'][^"']*csv[^"']*\.(?:png|gif|svg)["']/i.test(haystack) ||
      /\bclass\s*=\s*["'][^"']*(?:pi-file-csv|fa-file-csv|ui-icon-csv)[^"']*["']/i.test(haystack) ||
      /\bid\s*=\s*["'][^"']*csv[^"']*["']/i.test(haystack) ||
      /^csv$/i.test(label);
    out.push({ commandId, isCsv, label: label.slice(0, 60), attrs: attrs.slice(0, 200) });
  }
  return out;
}

/** Anything on the page mentioning csv/export, for diagnosing a redesign. */
function exportDiagnostics(html) {
  const hits = [];
  const re = /[^<>]{0,80}(?:csv|export|exporter)[^<>]{0,80}/gi;
  let m;
  while ((m = re.exec(html)) && hits.length < 25) {
    hits.push(m[0].replace(/\s+/g, ' ').trim());
  }
  return hits;
}

/** Field set for a JSF command POST: all hidden fields plus the command's id. */
function buildCommandFields(hidden, commandId, formId = 'ocrForm') {
  return { ...hidden, [formId]: formId, [commandId]: commandId };
}

/** Body for a JSF command POST: all hidden fields plus the command's own id. */
function buildCommandBody(hidden, commandId, formId = 'ocrForm') {
  return new URLSearchParams(buildCommandFields(hidden, commandId, formId)).toString();
}

/**
 * The same field set encoded as multipart/form-data.
 *
 * The only genuine capture of this portal's form declares
 * enctype="multipart/form-data". That matters more than it looks: if Mojarra's
 * multipart filter is installed and receives a urlencoded body, it does not
 * decode the postback at all — JSF simply re-renders the view and returns
 * HTTP 200 with HTML. So a wrong encoding never surfaces as an error status,
 * only as a page that quietly isn't the CSV.
 */
function buildMultipartBody(hidden, commandId, formId = 'ocrForm') {
  const fields = buildCommandFields(hidden, commandId, formId);
  const boundary = '----BreachBookFormBoundary' + Buffer.from(String(Object.keys(fields).length)).toString('hex');
  const parts = [];
  for (const [name, value] of Object.entries(fields)) {
    parts.push(
      `--${boundary}\r\n` +
        `Content-Disposition: form-data; name="${String(name).replace(/"/g, '%22')}"\r\n\r\n` +
        `${value}\r\n`
    );
  }
  parts.push(`--${boundary}--\r\n`);
  return { body: parts.join(''), contentType: `multipart/form-data; boundary=${boundary}` };
}

/**
 * AJAX (PrimeFaces partial) variant of the same postback. securelogic's live
 * 2026 fetch hypothesised the exporter is wired this way; it costs one extra
 * attempt to rule in or out.
 */
function buildAjaxBody(hidden, commandId, formId = 'ocrForm') {
  const fields = {
    ...buildCommandFields(hidden, commandId, formId),
    'javax.faces.source': commandId,
    'javax.faces.partial.event': 'click',
    'javax.faces.partial.execute': '@all',
    'javax.faces.partial.render': '@none',
    'javax.faces.behavior.event': 'action',
    'javax.faces.partial.ajax': 'true',
  };
  return new URLSearchParams(fields).toString();
}

/** Encodings to try, in order of evidential support. */
function commandEncodings(hidden, commandId, formId = 'ocrForm') {
  const multipart = buildMultipartBody(hidden, commandId, formId);
  return [
    { name: 'multipart', body: multipart.body, contentType: multipart.contentType },
    { name: 'urlencoded', body: buildCommandBody(hidden, commandId, formId), contentType: 'application/x-www-form-urlencoded' },
    { name: 'ajax', body: buildAjaxBody(hidden, commandId, formId), contentType: 'application/x-www-form-urlencoded' },
  ];
}

/** True when a response body plausibly IS the CSV export. */
function looksLikeCsv(body) {
  const text = String(body || '');
  if (!text.trim()) return false;
  if (/^\s*</.test(text) || /<html/i.test(text.slice(0, 500))) return false;
  const first = text.split('\n')[0] || '';
  return first.includes(',');
}

/** A short, diagnosable excerpt of a page that failed discovery. */
function excerpt(html, chars = 400) {
  const text = String(html || '').replace(/\s+/g, ' ').trim();
  return text.length > chars ? `${text.slice(0, chars)}...` : text;
}

module.exports = {
  buildCommandFields,
  buildMultipartBody,
  buildAjaxBody,
  commandEncodings,
  looksLikeCsv,
  listCommandCandidates,
  exportDiagnostics,
  commandIdFrom,
  extractHiddenInputs,
  extractViewState,
  extractFormAction,
  findCommandByLabel,
  findCsvExportCommand,
  buildCommandBody,
  decodeEntities,
  excerpt,
};
