// JSF form-driving helpers for the HHS OCR breach portal.
//
// The portal is a Mojarra/PrimeFaces JavaServer Faces app. There is no static
// CSV URL: obtaining the export requires a cookie-bound, multi-step POST
// sequence carrying a javax.faces.ViewState token that changes at every step.
//
// Every element id in that sequence (ocrForm:j_idt384 and friends) is
// auto-generated by Mojarra and SHIFTS WHENEVER HHS REDEPLOYS — a 2019 capture
// used j_idt364 for the same CSV link that a 2026 capture calls j_idt384.
// Nothing here may hardcode one. Commands are discovered structurally, by the
// label or icon a human would click, and a failed discovery throws with the
// surrounding markup so the breakage is diagnosable instead of silent.
//
// These functions are pure string-in/string-out so they can be tested without
// network access; the orchestration that uses them lives in hhs-ocr-fetch.js.

/** Collect every hidden input as name -> value. */
function extractHiddenInputs(html) {
  const out = {};
  const inputRe = /<input\b[^>]*>/gi;
  let m;
  while ((m = inputRe.exec(html))) {
    const tag = m[0];
    if (!/type\s*=\s*["']?hidden/i.test(tag)) continue;
    const name = /\bname\s*=\s*["']([^"']+)["']/i.exec(tag);
    if (!name) continue;
    const value = /\bvalue\s*=\s*["']([^"']*)["']/i.exec(tag);
    out[name[1]] = value ? decodeEntities(value[1]) : '';
  }
  return out;
}

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

/**
 * The ViewState token. Accepts the Jakarta Faces 4 spelling too, so a platform
 * upgrade downgrades to a clear error rather than a silent 'not found'.
 */
function extractViewState(hidden) {
  return hidden['javax.faces.ViewState'] ?? hidden['jakarta.faces.ViewState'] ?? null;
}

/** The <form> action attribute (may carry a path-encoded ;jsessionid=...). */
function extractFormAction(html, formId = 'ocrForm') {
  const re = new RegExp(`<form\\b[^>]*\\bid\\s*=\\s*["']${formId}["'][^>]*>`, 'i');
  const tag = re.exec(html);
  if (!tag) return null;
  const action = /\baction\s*=\s*["']([^"']+)["']/i.exec(tag[0]);
  return action ? decodeEntities(action[1]) : null;
}

/**
 * Find the JSF command id behind a link, by the visible text a human clicks.
 * Mojarra renders these as:
 *   <a href="#" onclick="mojarra.jsfcljs(document.getElementById('ocrForm'),
 *      {'ocrForm:j_idt39':'ocrForm:j_idt39'},'');return false">View HIPAA Breach Reports</a>
 */
function findCommandByLabel(html, label) {
  const anchorRe = /<a\b[^>]*onclick\s*=\s*"([^"]*mojarra\.jsfcljs[^"]*)"[^>]*>([\s\S]*?)<\/a>/gi;
  let m;
  const wanted = label.toLowerCase().replace(/\s+/g, ' ').trim();
  while ((m = anchorRe.exec(html))) {
    const text = m[2].replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim().toLowerCase();
    if (text.includes(wanted)) {
      const cmd = /\{\s*'([^']+)'\s*:/.exec(decodeEntities(m[1]));
      if (cmd) return cmd[1];
    }
  }
  return null;
}

/**
 * Find the CSV export command. The export icons (Excel, PDF, CSV, XML) are
 * siblings in one span, so selection MUST be by the CSV icon itself — picking
 * by position silently downloads a spreadsheet that the CSV parser will reject
 * or, worse, misread.
 */
function findCsvExportCommand(html) {
  const anchorRe = /<a\b[^>]*onclick\s*=\s*"([^"]*mojarra\.jsfcljs[^"]*)"[^>]*>([\s\S]*?)<\/a>/gi;
  let m;
  while ((m = anchorRe.exec(html))) {
    const inner = m[2];
    const isCsv =
      /<img\b[^>]*\b(?:alt|title)\s*=\s*["'][^"']*csv[^"']*["']/i.test(inner) ||
      /\bsrc\s*=\s*["'][^"']*csv[^"']*\.(?:png|gif|svg)["']/i.test(inner);
    if (!isCsv) continue;
    const cmd = /\{\s*'([^']+)'\s*:/.exec(decodeEntities(m[1]));
    if (cmd) return cmd[1];
  }
  return null;
}

/** Body for a JSF command POST: all hidden fields plus the command's own id. */
function buildCommandBody(hidden, commandId, formId = 'ocrForm') {
  const body = { ...hidden, [formId]: formId, [commandId]: commandId };
  return new URLSearchParams(body).toString();
}

/** A short, diagnosable excerpt of a page that failed discovery. */
function excerpt(html, chars = 400) {
  const text = String(html || '').replace(/\s+/g, ' ').trim();
  return text.length > chars ? `${text.slice(0, chars)}...` : text;
}

module.exports = {
  extractHiddenInputs,
  extractViewState,
  extractFormAction,
  findCommandByLabel,
  findCsvExportCommand,
  buildCommandBody,
  decodeEntities,
  excerpt,
};
