name = "breachledger-alerts"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "breachledger"
database_id = "13473ea8-386a-45f1-a941-e4f1c7b795ec"

[[kv_namespaces]]
binding = "HOT"
id = "27fd610a89594889984b0f1985fa7539"
